### ISSUE TITLE
Docker Error Terraform Apply

### ISSUE THREAD

**Issue by L0d0c** [teticio/lambda-selenium#1]
Hello, 
When I do the command "terraform apply -auto-approve" I get the following terraform error despite numerous tests to resolve my problem:

│ Error: failed to read dockerfile: unexpected EOF
│
│
│
│   with module.docker_image.docker_image.this,
│   on .terraform\modules\docker_image\modules\docker-build\main.tf line 12, in resource "docker_image" "this":
│   12: resource "docker_image" "this" {

**Comment by teticio** [comment]
That's weird... Can you tell me what platform you are running on? And what version of terraform?

**Comment by teticio** [comment]
You could also try
```
export TF_LOG=DEBUG
terraform apply -auto-approve
```
and see if that gives a clue. Appreciate it!

**Comment by L0d0c** [comment]
hello, 
My platform is Windows11, I test with MacOS and all is work, thanks for your help
Thanks for your good works :)
