### ISSUE TITLE
example test_seleniun,py task times out 

### ISSUE THREAD

**Issue by BlazJurisic** [teticio/lambda-selenium#2]
I did the repro running:

```
python test_selenium.py
```

all regions and account settings are correct, I get this error message:
```
Exception: {'errorMessage': '2024-02-12T10:45:49.661Z  Task timed out after 30.01 seconds'}
```

**Comment by teticio** [comment]
I just ran it from scratch and "it works for me". Can you try again / look at the logs in Cloudwatch?

**Comment by teticio** [comment]
I should add that every now and again you get timeouts. It is difficult to handle every possible case so the best thing is to retry.

**Comment by BlazJurisic** [comment]
please explain me why is this happening, running python example.py works and finishes in 4 seconds, I tried to increase timeout in terraform code to 60 seconds but it times out every time

**Comment by BlazJurisic** [comment]
great project btw, I was starting to build the solution myself and found your repo, thank you

**Comment by BlazJurisic** [comment]
I figured out the mistake was my obscure error. Thank you

**Comment by teticio** [comment]
Thanks! Glad you were able to figure it out.
